name: deploy
on:
  push:
    paths:
      - "README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./LearnThreejs
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: list
        run: ls
      - name: install package
        run: yarn
      - name: build
        run: yarn build

      - name: check
        run: pwd & ls
      - name: start server
        run: yarn deploy
