name: deploy
on:
  push:
    paths:
      - "README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./LearnThreejs
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: list
        run: ls
      - name: install package
        run: yarn
      - name: start server
        run: yarn start
