name: deploy
on:
  push:
    paths:
      - "README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./LearnThreejs
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: list
        run: ls
      - name: install package
        run: yarn
      - name: build
        run: yarn build
      - name: check
        run: pwd & ls
      - name: start server
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL}}
          MY_NAME: ${{ secrets.MY_NAME}}
          MY_GH_NAME: ${{ secrets.MY_GH_NAME}}
          MY_GH_PASS: ${{ secrets.MY_GH_PASS}}
        run: git config --global user.email "env.MY_EMAIL" &
          git config --global user.name "env.MY_NAME" &
          git remote set-url origin https://env.MY_GH_NAME:env.MY_GH_PASS@github.com/env.MY_GH_NAME/LearnThreejs.git
          yarn deploy
